language: python
python:
  - "3.5"
sudo: false
addons:
  apt:
    packages:
    - gcc-4.6-base:i386
    - libc6:i386
    - libfreetype6:i386
    - libgcc1:i386
    - libssl1.0.0:i386
    - libuuid1:i386
    - zlib1g:i386
before_install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git pull origin $TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH
  - pushd scripts
  - ./install_git.sh
  - cd git-2.6.5
  - export GIT_EXEC_PATH=`pwd`
  - export PATH=`pwd`:$PATH
  - export GITPERLLIB=`pwd`/perl/blib/lib
  - popd
  - git --version
before_script:
  - wget -O - https://raw.githubusercontent.com/pillar-markup/book-skeleton/master/download.sh | bash
script:
  - cd scripts
  - ./build.sh
